name: Deploy Node.js site on 85server
on:
  push:
    branches: [ master ]
jobs:
  build:
    name: deploy
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.15.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        
    steps:
        - name: Checkout
          uses: actions/checkout@v2
          
        - name: Setup Node using node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v2
          with:
            node-version:  ${{ matrix.node-version }}
          
        - name: Detect package manager 
          id: detect-package-manager
          run: |
           npm install -f
           npm install -g pm2
           pm2 start index.js
         
        - name: Deploy file to server
          uses: wlixcc/SFTP-Deploy-Action@v1.2.4
          with:
            username: ${{ secrets.FTP_USERNAME }}
            server: ${{ secrets.FTP_SERVER }}
            port: ${{ secrets.FTP_PORT }}
            password: ${{ secrets.FTP_PASSWORD }}
            ssh_private_key: ${{ secrets.SSH_PUBLIC_KEY }}
            local_path: './*'
            remote_path: '/var/www/html/nodejs_pipeline'
            sftp_only: true,
            args: '-o ConnectTimeout=5'
