on:
  push:
    branches: [ master, Development ]
jobs:
  build:
    name: deploy
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Deploy file
          uses: wlixcc/SFTP-Deploy-Action@v1.2.4
          with:
            username: ${{ secrets.FTP_USERNAME }}
            server: ${{ secrets.FTP_SERVER }}
            port: ${{ secrets.FTP_PORT }}
            remote_path: '/var/www/html/testing_pipeline'
            sftp_only: true
            password: ${{ secrets.FTP_PASSWORD }}yyy
